/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./App.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#291800",
        "tertiary-fixed-dim": "#e8c08a",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-container": "#54647a",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#b7c8e1",
        "on-error": "#ffffff",
        "tertiary-container": "#3e2700",
        "outline-variant": "#c5c6cf",
        "inverse-primary": "#b6c6ef",
        "surface-container": "#edeeef",
        "on-surface-variant": "#44474e",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "surface-container-low": "#f3f4f5",
        "secondary": "#505f76",
        "on-primary-container": "#8293b8",
        "on-background": "#191c1d",
        "on-tertiary-container": "#b08d5b",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffddb1",
        "primary-fixed-dim": "#b6c6ef",
        "inverse-on-surface": "#f0f1f2",
        "primary-fixed": "#d8e2ff",
        "surface-bright": "#f8f9fa",
        "on-primary-fixed-variant": "#364768",
        "background": "#f8f9fa",
        "surface": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "on-primary-fixed": "#081b3a",
        "on-error-container": "#93000a",
        "outline": "#75777f",
        "surface-tint": "#4e5e81",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "primary-container": "#1a2b4b",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-fixed-variant": "#38485d",
        "surface-variant": "#e1e3e4",
        "surface-container-highest": "#e1e3e4",
        "primary": "#031635",
        "surface-dim": "#d9dadb",
        "on-tertiary-fixed-variant": "#5d4217",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "tertiary": "#231400"
      },
      borderRadius: {
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "4px",
        "gutter": "24px",
        "xl": "48px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "container-max": "1280px"
      }
    },
  },
  plugins: [],
}
